import test from 'node:test';
import assert from 'node:assert/strict';
import {auditGeometry} from '../src/audit.mjs';
const line=(id,a,b,extra={})=>({primitiveId:id,net:'N',layer:1,startX:a[0],startY:a[1],endX:b[0],endY:b[1],lineWidth:8,...extra});
const pair=()=>[line('a',[0,0],[100,0]),line('b',[100,0],[100,100])];
const run=(lines,extra={},options={})=>auditGeometry({units:'mil',lines,pads:[],vias:[],...extra},options);
test('ordinary 90-degree endpoint is counted once',()=>{const r=run(pair());assert.equal(r.counts.ordinaryBadJoints,1);assert.equal(r.counts.non45Segments,0);assert.equal(r.engineeringRelease,'NOT_EVALUATED');});
test('non-45 segment is independent of corner checks',()=>{const r=run([line('a',[0,0],[20,7])]);assert.equal(r.counts.non45Segments,1);assert.equal(r.counts.ordinaryBadJoints,0);});
test('board outline is excluded from copper audit',()=>{const r=run(pair().map(l=>({...l,layer:11})));assert.equal(r.counts.copperLines,0);assert.equal(r.counts.ordinaryBadJoints,0);});
test('three-way branch counts orthogonal pairs separately',()=>{const r=run([line('a',[0,0],[100,0]),line('b',[0,0],[-100,0]),line('c',[0,0],[0,100])]);assert.equal(r.counts.branchNodes,1);assert.equal(r.counts.orthogonalPairs.branch,2);assert.equal(r.counts.ordinaryBadJoints,0);assert.equal(r.verdict,'REVIEW_REQUIRED');});
test('pad center category is not a free pass',()=>{const r=run(pair(),{pads:[{x:100,y:0,net:'N',layer:1}]});assert.equal(r.counts.padNodes,1);assert.equal(r.counts.ordinaryBadJoints,0);assert.equal(r.verdict,'REVIEW_REQUIRED');});
test('through-via center has its own category',()=>{const r=run(pair(),{vias:[{x:100,y:0,net:'N',viaType:0,holeDiameter:12}]});assert.equal(r.counts.viaNodes,1);assert.equal(r.counts.orthogonalPairs.via,1);});
test('SMD on other layer does not hide an ordinary joint',()=>{const r=run(pair(),{pads:[{x:100,y:0,net:'N',layer:2}]});assert.equal(r.counts.ordinaryBadJoints,1);});
test('unplated MULTI pad does not imply copper connection',()=>{const r=run(pair(),{pads:[{x:100,y:0,net:'N',layer:12,metallization:false}]});assert.equal(r.counts.ordinaryBadJoints,1);});
test('different net or layer endpoints never merge',()=>{assert.equal(run([pair()[0],{...pair()[1],net:'X'}]).counts.ordinaryBadJoints,0);assert.equal(run([pair()[0],{...pair()[1],layer:2}]).counts.ordinaryBadJoints,0);});
test('neighbor-cell epsilon joint is detected',()=>{const r=run([line('a',[-100,0],[0.019,0]),line('b',[0.021,0],[0.021,100])]);assert.equal(r.counts.ordinaryBadJoints,1);});
test('explicit mm and mil agree',()=>{const mil=run(pair()),mm=run(pair().map(l=>{const s={...l};for(const k of ['startX','startY','endX','endY','lineWidth'])s[k]*=0.0254;return s;}),{units:'mm'});assert.deepEqual(mil.counts,mm.counts);assert.ok(Math.abs(mm.netStatistics[0].segmentLengthSumMil-200)<1e-6);});
test('sub-tolerance segment is reported without dividing by zero',()=>{assert.equal(run([line('a',[0,0],[0.001,0])]).counts.degenerateSegments,1);});
test('missing context is explicit and never certified',()=>{const r=auditGeometry({units:'mil',lines:[]});assert.deepEqual(r.warnings,['Pad centers unavailable: ordinary-joint classification is provisional','Via centers unavailable: ordinary-joint classification is provisional','Arc geometry unavailable: joint and length statistics cover straight segments only']);assert.equal(r.engineeringRelease,'NOT_EVALUATED');});
test('malformed geometry and units are rejected',()=>{assert.throws(()=>auditGeometry({lines:[]}));assert.throws(()=>run([line('a',[0,0],[NaN,1])]));assert.throws(()=>run([],{}, {toleranceMil:10}));assert.throws(()=>run([],{}, {detailLimit:-1}));});
test('duplicate IDs cannot inflate input metrics silently',()=>{assert.throws(()=>run([pair()[0],pair()[0]]),/Duplicate/);});
test('details truncate but counts remain full',()=>{const r=run(pair(),{}, {detailLimit:0});assert.equal(r.counts.ordinaryBadJoints,1);assert.equal(r.details.ordinaryBadJoints.length,0);assert.equal(r.detailsTruncated,true);});
test('audit never mutates caller snapshot',()=>{const input={units:'mil',lines:pair(),pads:[],vias:[]};const before=JSON.stringify(input);auditGeometry(input);assert.equal(JSON.stringify(input),before);});
