import test from 'node:test';
import assert from 'node:assert/strict';
import { validatePlan } from '../src/plan.mjs';
const base=op=>({schema:'easyeda-pcb-plan/v2',intent:'Respect screw hole copper clearance',target:{documentUuid:'pcb'},units:'mm',phase:'route',constraints:{allowedLayers:['TOP','BOTTOM','INNER_1','INNER_2'],circularKeepouts:[{name:'MH1',center:[0,0],diameter:6}]},operations:[op]});
const via=x=>({id:'v',type:'via.create',net:'GND',position:[x,0],holeDiameter:.3,diameter:.6});
const line=(y,width=.15)=>({id:'l',type:'line.create',net:'GND',layer:'TOP',start:[-5,y],end:[5,y],width});
test('circle guard rejects a via centered in a screw zone',()=>assert.throws(()=>validatePlan(base(via(0))),/circular keepout/));
test('circle guard includes the annular copper ring, not only the drill',()=>assert.throws(()=>validatePlan(base(via(3.2))),/circular keepout/));
test('circle guard accepts a correctly cleared through via',()=>assert.equal(validatePlan(base(via(3.31))).operations.length,1));
test('circle guard rejects a crossing segment with both endpoints outside',()=>assert.throws(()=>validatePlan(base(line(0))),/circular keepout/));
test('circle guard includes track width',()=>assert.throws(()=>validatePlan(base(line(3.05))),/circular keepout/));
test('circle guard applies to inner-layer tracks',()=>assert.throws(()=>validatePlan(base({...line(0),layer:'INNER_2'})),/circular keepout/));
test('circle guard checks widening modifications',()=>assert.throws(()=>validatePlan(base({id:'w',type:'line.modify',primitiveId:'trace',expected:{net:'GND',layer:1,startX:-5,startY:3.1,endX:5,endY:3.1,lineWidth:.15},set:{lineWidth:.5}})),/circular keepout/));
test('circle guard checks moved vias',()=>assert.throws(()=>validatePlan(base({id:'m',type:'via.modify',primitiveId:'via',expected:{net:'GND',x:4,y:0,holeDiameter:.3,diameter:.6,viaType:0},set:{x:2}})),/circular keepout/));
test('circle guard preserves explicit mm-to-mil units',()=>{const p=base(via(3.31));p.units='mil';p.operations[0].position[0]/=.0254;p.operations[0].holeDiameter/=.0254;p.operations[0].diameter/=.0254;p.constraints.circularKeepouts[0].diameter/=.0254;assert.equal(validatePlan(p).operations.length,1);});
test('invalid circle geometry is rejected before any client operation',()=>{const p=base(via(4));p.constraints.circularKeepouts[0].diameter=-6;assert.throws(()=>validatePlan(p),/Positive/);});
