import test from 'node:test';
import assert from 'node:assert/strict';
import {validatePlan} from '../src/plan.mjs';
import {constraintRuntime} from '../src/constraint-runtime.mjs';
import {pcbToolsRuntime} from '../src/pcb-tools-runtime.mjs';
const target={documentUuid:'pcb',projectUuid:'project'};
const base=()=>({dmt_SelectControl:{getCurrentDocumentInfo:async()=>({uuid:'pcb',documentType:3})},dmt_Project:{getCurrentProjectInfo:async()=>({uuid:'project'})}});
const plan=extra=>({schema:'easyeda-pcb-plan/v2',intent:'Test explicit pour priority policy',target,units:'mil',phase:'finish',operations:[{id:'p',type:'pour.create',net:'GND',layer:'TOP',pourName:'TEST',points:[[0,0],[100,0],[100,100],[0,100]],...extra}]});
test('F01 omitted priority explicitly normalizes to native policy without a fabricated number',()=>{const result=validatePlan(plan({}));assert.equal(result.operations[0].priorityPolicy,'native');assert.equal('pourPriority' in result.operations[0].state,false)});
test('F02 native priority policy cannot silently override an explicit number',()=>{assert.throws(()=>validatePlan(plan({priorityPolicy:'native',priority:5})),/cannot also specify/)});
test('F03 reverse duplicate pad pair is a verified no-op without a native write',async()=>{let writes=0;const current={name:'G',padPairs:[['R1:1','R1:2']]};const eda={...base(),pcb_Drc:{getAllPadPairGroups:async()=>[current],addPadPairToPadPairGroup:async()=>{writes++;return true}}};const result=await constraintRuntime(eda,{target,kind:'manage',operation:{action:'addMembers',groupType:'padPairGroup',name:'G',expected:current,members:[['R1:2','R1:1']]}});assert.equal(result.status,'already_modified');assert.equal(writes,0)});
test('F04 self-pair is rejected without creating a group',async()=>{let writes=0;const eda={...base(),pcb_Drc:{getAllPadPairGroups:async()=>[],createPadPairGroup:async()=>{writes++;return true}}};await assert.rejects(constraintRuntime(eda,{target,kind:'manage',operation:{action:'create',groupType:'padPairGroup',name:'G',expected:null,definition:{padPairs:[['R1:1','R1:1']]}}}),/distinct endpoint/);assert.equal(writes,0)});
test('F05 a user-created group during asynchronous preflight is not overwritten',async()=>{let calls=0,writes=0;const groups=[];const eda={...base(),pcb_Drc:{getAllNetClasses:async()=>groups,createNetClass:async()=>{writes++;return true}}};eda.dmt_SelectControl.getCurrentDocumentInfo=async()=>{if(++calls===3)groups.push({name:'G',nets:['MANUAL'],color:null});return {uuid:'pcb',documentType:3}};await assert.rejects(constraintRuntime(eda,{target,kind:'manage',operation:{action:'create',groupType:'netClass',name:'G',expected:null,definition:{nets:['GND'],color:null}}}),/old-value assertion/);assert.equal(writes,0)});
function repour(){let writes=0;let fills=[{primitiveId:'f1',pourPrimitiveId:'p1',pourFills:[[1]]},{primitiveId:'f2',pourPrimitiveId:'p2',pourFills:[[1]]}];const eda={...base(),sys_Environment:{getEditorCurrentVersion:async()=> '3.2.186'},pcb_PrimitivePour:{getAll:async()=>[{primitiveId:'p1',rebuildCopperRegion:async()=>{writes++;fills[1].pourFills=[[2]];return fills[0]}},{primitiveId:'p2'}]},pcb_PrimitivePoured:{getAll:async()=>structuredClone(fills)}};return {eda,writes:()=>writes};}
test('F06 known client partial repour needs explicit collateral scope acceptance',async()=>{const f=repour();await assert.rejects(pcbToolsRuntime(f.eda,{target,kind:'rebuildPours',pourIds:['p1']}),/allowCollateralRebuild/);assert.equal(f.writes(),0)});
test('F07 non-target fill changes are reported independently of target acknowledgement',async()=>{const f=repour();const result=await pcbToolsRuntime(f.eda,{target,kind:'rebuildPours',pourIds:['p1'],allowCollateralRebuild:true});assert.equal(f.writes(),1);assert.equal(result.scopeChangedOutsideRequest,true);assert.deepEqual(result.nonTargetFillChanges,[{primitiveId:'f2',boundaryId:'p2',action:'modified'}]);assert.deepEqual(result.unverifiedRebuildIds,[])});
