import test from 'node:test';
import assert from 'node:assert/strict';
import { regionReadRuntime } from '../src/region-read.mjs';
import { createKeepoutModel } from '../src/keepout.mjs';
const target={documentUuid:'0123456789abcdef',projectUuid:'p',windowId:'w',tabId:'t'};
const head=JSON.stringify({type:'DOCHEAD'})+'||'+JSON.stringify({docType:'PCB',uuid:target.documentUuid})+'|\n';
const make=flags=>head+JSON.stringify({type:'REGION',id:'1111111111111111',ticket:1})+'||'+JSON.stringify({layerId:12,locked:true,width:.2,prohibitType:flags,path:[[0,0,'L',1,0,1,1,0,0]],name:'TEST',regionType:'PROHIBIT'})+'|';
const edaFor=get=>({dmt_SelectControl:{getCurrentDocumentInfo:async()=>({uuid:target.documentUuid,documentType:3,tabId:'t'})},dmt_Project:{getCurrentProjectInfo:async()=>({uuid:'p'})},sys_FileManager:{getDocumentSource:get}});
test('region reader preserves native VIA and all six rules',async()=>{const r=await regionReadRuntime(edaFor(async()=>make(['COMPONENT','VIA','TRACK','FILL','COPPER','PLANE'])),{target},createKeepoutModel);assert.deepEqual(r.items[0].ruleType,[2,3,5,6,7,8]);assert.equal(r.total,1);});
test('region reader rejects drift rather than returning stale rules',async()=>{let calls=0;await assert.rejects(regionReadRuntime(edaFor(async()=>make(calls++?['VIA']:['COPPER'])),{target},createKeepoutModel),/changed during two reads/);});
test('region reader rejects unknown native restrictions',async()=>{await assert.rejects(regionReadRuntime(edaFor(async()=>make(['UNKNOWN'])),{target},createKeepoutModel),/Unrecognized/);});
test('region reader pages without fabricating empty completeness',async()=>{const r=await regionReadRuntime(edaFor(async()=>make(['VIA'])),{target,offset:1,limit:1},createKeepoutModel);assert.equal(r.total,1);assert.equal(r.items.length,0);});
