import test from 'node:test';
import assert from 'node:assert/strict';
import {captureSnapshotRuntime,inspectPinmapRuntime} from '../src/verification.mjs';
import {evaluateSyncExpectations} from '../src/sync-expectations.mjs';
import {compareSnapshots} from '../src/inspection.mjs';
import {inspectAllSilkscreen} from '../src/silkscreen-all.mjs';
import {loadPlanSource} from '../src/bridge.mjs';
const target={documentUuid:'pcb',projectUuid:'project',windowId:'window'};
const document={uuid:'pcb',documentType:3,parentProjectUuid:'project'};
const eda=()=>({dmt_SelectControl:{getCurrentDocumentInfo:async()=>document},dmt_Project:{getCurrentProjectInfo:async()=>({uuid:'project'})}});
function reader({netlist={components:{}},layers=[],duplicate=false}={}){return async(_,q)=>{if(q.kind==='snapshot')return {document,units:'mil',layers,...Object.fromEntries(q.include.map(k=>[k,k==='pads'&&duplicate?[{primitiveId:'free1'},{primitiveId:'free1'}]:[]]))};if(q.kind==='netlist')return netlist;throw Error('Unexpected '+q.kind)}}
test('R301 failed netlist boolean cannot be captured as complete PCB data',async()=>assert.rejects(captureSnapshotRuntime(eda(),{target},reader({netlist:false}),async()=>({})),/netlist.*unavailable|invalid.*netlist/i));
test('R302 failed layer boolean cannot be captured as a valid stackup',async()=>assert.rejects(captureSnapshotRuntime(eda(),{target},reader({layers:false}),async()=>({})),/layer.*unavailable|invalid.*layer/i));
test('R303 duplicate standalone pads are not silently discarded by the snapshot map',async()=>assert.rejects(captureSnapshotRuntime(eda(),{target},reader({duplicate:true}),async()=>({})),/duplicate/i));
test('R304 null rule data explicitly marks the captured metadata as incomplete',async()=>{const r=await captureSnapshotRuntime(eda(),{target},reader(),async()=>({netRules:{available:true,value:null}}));assert.ok(r.coverage.unavailableConstraintFields.includes('netRules'));assert.equal(r.coverage.metadataComplete,false)});
test('R305 invalid metadata is not included in verified comparison scope',()=>{const snapshot={document,units:'mil',lines:[],netlist:false,layers:null,constraints:null};const r=compareSnapshots(snapshot,snapshot);assert.deepEqual(r.comparedData,[]);assert.deepEqual(r.unverifiedData,['netlist','layers','constraints']);assert.equal(r.fullSnapshotUnchanged,null)});
test('R306 full silkscreen inspection rejects explicitly requested missing labels',async()=>{await assert.rejects(inspectAllSilkscreen({target,ids:['missing']},async q=>({total:0,offset:q.offset,items:[],hasMore:false,missingIds:['missing']})),/missing|not found|unavailable/i)});
test('R307 inline plan data obeys the same size cap as file data',async()=>{await assert.rejects(loadPlanSource({plan:{payload:'x'.repeat(100)}},{maxBytes:32}),/exceeds/)});
test('R308 misspelled ECO postcondition cannot be ignored and verified',()=>{assert.throws(()=>evaluateSyncExpectations({components:[{uniqueId:'u1',designator:'R1'}],pads:[]},{components:[{uniqueId:'u1',designatr:'R2'}]}),/unknown|unsupported/i)});
test('R309 contradictory component absence and attribute goals reject before import',()=>{assert.throws(()=>evaluateSyncExpectations({components:[],pads:[]},{components:[{uniqueId:'u1',present:false,designator:'R1'}]}),/absence|present|contradict/i)});
test('R310 repeated physical pin IDs cannot produce a verified pin map',async()=>{const e=eda();e.pcb_PrimitiveComponent={getAll:async()=>[{primitiveId:'c1',designator:'CN1',x:0,y:0,layer:1,rotation:0}],getAllPinsByPrimitiveId:async()=>[{primitiveId:'p1',padNumber:'1',net:'GND',x:0,y:0},{primitiveId:'p1',padNumber:'1',net:'GND',x:0,y:0}]};await assert.rejects(inspectPinmapRuntime(e,{target,componentIds:['c1']}),/duplicate/i)});
