import test from 'node:test';
import assert from 'node:assert/strict';
import { inspectPinmapRuntime, captureSnapshotRuntime, captureSnapshot } from '../src/verification.mjs';
import { inspectAllSilkscreen } from '../src/silkscreen-all.mjs';
import { constraintRuntime } from '../src/constraint-runtime.mjs';
const target={documentUuid:'pcb',projectUuid:'project',windowId:'window'};
const document={uuid:'pcb',documentType:3,parentProjectUuid:'project'};
const base=()=>({dmt_SelectControl:{getCurrentDocumentInfo:async()=>document},dmt_Project:{getCurrentProjectInfo:async()=>({uuid:'project'})}});
function pins(){const eda=base();let values=[{primitiveId:'p1',padNumber:'1',net:'5V',x:10,y:20},{primitiveId:'p2',padNumber:'2',net:'GND',x:10,y:30}];eda.pcb_PrimitiveComponent={getAll:async()=>[{primitiveId:'c1',designator:'CN1',x:10,y:20,rotation:90,layer:2}],getAllPinsByPrimitiveId:async()=>structuredClone(values)};return {eda,set:v=>values=v};}
test('V01 real pin mapping preserves pad number, net and bottom-side pose',async()=>{const f=pins();const r=await inspectPinmapRuntime(f.eda,{target,designators:['CN1']});assert.equal(r.padCount,2);assert.equal(r.items[0].layer,2);assert.equal(r.items[0].pads[0].net,'5V');assert.equal(r.allExpectedMatch,null)});
test('V02 expected swapped supply is reported as a mismatch without writes',async()=>{const f=pins();const r=await inspectPinmapRuntime(f.eda,{target,componentIds:['c1'],expected:[{componentId:'c1',padNumber:'1',net:'GND'}]});assert.equal(r.mismatchCount,1);assert.equal(r.allExpectedMatch,false)});
test('V03 ambiguous duplicate designators are rejected',async()=>{const f=pins();f.eda.pcb_PrimitiveComponent.getAll=async()=>[{primitiveId:'c1',designator:'CN1'},{primitiveId:'c2',designator:'CN1'}];await assert.rejects(inspectPinmapRuntime(f.eda,{target,designators:['CN1']}),/ambiguous/)});
test('V04 unavailable pins do not count as a valid connector with zero pins',async()=>{const f=pins();f.eda.pcb_PrimitiveComponent.getAllPinsByPrimitiveId=async()=>undefined;await assert.rejects(inspectPinmapRuntime(f.eda,{target,componentIds:['c1']}),/unavailable/)});
test('V05 changed net between pin reads aborts',async()=>{const f=pins();let count=0;f.eda.pcb_PrimitiveComponent.getAllPinsByPrimitiveId=async()=>[{primitiveId:'p',padNumber:'1',net:++count===1?'5V':'GND',x:0,y:0}];await assert.rejects(inspectPinmapRuntime(f.eda,{target,componentIds:['c1']}),/changed/)});
test('V06 both selectors or none are invalid',async()=>{const f=pins();for(const selectors of [{},{designators:['CN1'],componentIds:['c1']}])await assert.rejects(inspectPinmapRuntime(f.eda,{target,...selectors}),/exactly one/)});
const textItems=()=>Array.from({length:101},(_,i)=>({primitiveId:'t'+i,visibility:'text-object',layer:3,bounds:{minX:i===100?0:i*10,maxX:i===100?1:i*10+1,minY:0,maxY:1},warnings:[]}));
const pager=items=>async request=>({ok:true,total:items.length,offset:request.offset,items:items.slice(request.offset,request.offset+100),hasMore:request.offset+100<items.length});
test('V07 full-scope silk finds a collision across the page 100/101 boundary',async()=>{const r=await inspectAllSilkscreen({target,limit:1},pager(textItems()));assert.equal(r.overlapCount,1);assert.equal(r.evaluatedObjectCount,101);assert.equal(r.items.length,1);assert.deepEqual(r.sameLayerBBoxOverlaps[0],['t0','t100'])});
test('V08 hidden attributes do not count as readable overlaps',async()=>{const items=textItems();items[100].visibility='hidden-attribute';const r=await inspectAllSilkscreen({target},pager(items));assert.equal(r.overlapCount,0);assert.equal(r.visibleObjectCount,100)});
test('V09 overlap details may be capped without losing total count',async()=>{const r=await inspectAllSilkscreen({target,detailLimit:0},pager(textItems()));assert.equal(r.overlapCount,1);assert.equal(r.sameLayerBBoxOverlaps.length,0);assert.equal(r.overlapDetailsTruncated,true)});
test('V10 all-scope audit rejects oversized target instead of partial success',async()=>{await assert.rejects(inspectAllSilkscreen({target,maximumObjects:50},pager(textItems())),/exceeds/)});
test('V11 changing total during page collection aborts',async()=>{await assert.rejects(inspectAllSilkscreen({target},async q=>({total:q.offset?102:101,offset:q.offset,items:textItems().slice(q.offset,q.offset+100),hasMore:!q.offset})),/count changed/)});
test('V12 different second full read aborts visual-data acceptance',async()=>{let calls=0;await assert.rejects(inspectAllSilkscreen({target},async q=>{const items=textItems();if(++calls>2)items[0].text='manual edit';return pager(items)(q)}),/changed/)});
function snapshotFixture(){let pinsRead=0;const read=async(e,q)=>{if(q.kind==='snapshot')return {document,units:'mil',layers:[],...Object.fromEntries(q.include.map(k=>[k,k==='components'?[{primitiveId:'c1'}]:[]]))};if(q.kind==='pins'){pinsRead++;return [{componentId:'c1',pads:[{primitiveId:'p1',padNumber:'1',net:'GND'}]}]};if(q.kind==='netlist')return {components:{}};};return {read,count:()=>pinsRead};}
test('V13 full snapshot contains component pins absent from standalone getAll',async()=>{const f=snapshotFixture();const r=await captureSnapshotRuntime(base(),{target},f.read,async()=>({netRules:{available:true,value:{}}}));assert.equal(r.pads.length,1);assert.equal(r.pads[0].componentPrimitiveId,'c1');assert.equal(f.count(),2);assert.equal(r.coverage.categories.length,12)});
test('V14 snapshot discloses failed constraint field rather than inventing empty rules',async()=>{const f=snapshotFixture();const r=await captureSnapshotRuntime(base(),{target},f.read,async()=>({netRules:{available:true,error:'not available',value:null}}));assert.deepEqual(r.coverage.unavailableConstraintFields,['netRules'])});
test('V15 snapshot rejects inconsistent two-pass data',async()=>{const f=snapshotFixture();let count=0;await assert.rejects(captureSnapshotRuntime(base(),{target},async(e,q)=>{const v=await f.read(e,q);if(q.kind==='netlist')return {revision:++count};return v},async()=>({})),/changed/)});
test('V16 snapshot rejects relative output before any Bridge access',async()=>{await assert.rejects(captureSnapshot({target,outputPath:'result.json'}),/absolute/)});
test('V17 failed constraint list cannot become an empty group collection',async()=>{const e={...base(),pcb_Drc:{getAllNetClasses:async()=>undefined}};await assert.rejects(constraintRuntime(e,{target,kind:'read'}),/enumeration unavailable/)});
